Browser: !!python/unicode ''
GitPassword: !!python/unicode ''
GitRepo: !!python/unicode ''
GitUser: !!python/unicode ''
SeleniumHost: !!python/unicode ''
SeleniumOs: !!python/unicode ''
SeleniumPort: 4444
TestPath: !!python/unicode ''
